apiVersion: v1                 # Specifies the version of the Kubernetes API to use
kind: Pod                     # Declares this resource as a Pod
metadata:
  name: mylivenessprobe       # Name of the Pod
  labels:
    test: liveness            # Label to identify or group this Pod

spec:
  containers:
    - name: liveness          # Name of the container inside the Pod
      image: ubuntu           # Base image used for the container (Ubuntu OS)
      args:
        - /bin/sh             # Shell to execute the command
        - -c                  # Tells the shell to run the following string as a command
        - touch /tmp/healthy; sleep 1000  # Creates a file and keeps container running
      livenessProbe:          # Probe to check if the container is alive
        exec:
          command:
            - cat             # Runs 'cat /tmp/healthy' as health check
            - /tmp/healthy    # If this file is missing, the probe fails
        initialDelaySeconds: 5  # Wait 5 seconds before starting first probe
        periodSeconds: 5        # Check every 5 seconds
        timeoutSeconds: 30      # Wait up to 30 seconds for the probe to finish
