apiVersion: v1
kind: Pod
metadata:
  name: initcontainer
spec:
  initContainers:
    - name: c1
      image: ubuntu:latest
      command: ["/bin/sh", "-c", "echo Imtiaz Doing K8 training > /tmp/xchange/testfile; sleep 30"]
      volumeMounts:
        - name: xchange
          mountPath: "/tmp/xchange"
  containers:
    - name: c2
      image: ubuntu:latest
      command: ["/bin/bash", "-c", "while true; do echo `cat /tmp/data/testfile`; sleep 1; done"]
      volumeMounts:
        - name: xchange
          mountPath: "/tmp/data"
  volumes:
    - name: xchange
      emptyDir: {}

