apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
spec:
  parallelism: 5                           # Runs 5 pods in parallel
  activeDeadlineSeconds: 10                # Wait for 20 seconds then wait for 10 more seconds and delete the pods.
  template:
    metadata:
      name: testjob
    spec:
      containers:
        - name: counter
          image: centos:7
          command: ["/bin/bash", "-c", "echo Job Parallism Example; sleep 20"]
      restartPolicy: Never
