apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplica
spec:
  replicas: 2
  selector:
    myname: imtiaz
  template:
    metadata:
      name: testpod6
      labels:
        myname: imtiaz
    spec:
      containers:
        - name: c00
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo Hello-imtiaz; sleep 5; done"]
