apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs
spec:
  replicas: 2
  selector:
    matchExpressions:
      - key: browser
        operator: In
        values:
          - Firefox
          - chrome
          - edge
      - key: env
        operator: NotIn
        values:
          - production
  template:
    metadata:
      labels:
        browser: Firefox
    spec:
      containers:
        - name: c00
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo Firefox Test; sleep 5 ; done"]
